language: rust
rust:
- stable
before_install:
- sudo apt update
- sudo apt install -y libudev-dev
script:
- cargo build --release
deploy:
  provider: releases
  api_key: "$GITHUB_API_KEY"
  file: target/release/razer-naga-2014-key-remap
  skip_cleanup: true
  on:
    tags: true
