# Valid key values are:
# Esc, F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12,
# Grave, _1, _2, _3, _4, _5, _6, _7, _8, _9, _0, Minus, _Equal, BackSpace,
# Tab, Q, W, E, R, T, Y, U, I, O, P, LeftBrace, RightBrace, BackSlash,
# CapsLock, A, S, D, F, G, H, J, K, L, SemiColon, Apostrophe, Enter
# LeftShift, Z, X, C, V, B, N, M, Comma, Dot, Slash, RightShift
# LeftControl, LeftMeta, LeftAlt, Space, RightAlt, RightMeta, RightControl
#
# SysRq, ScrollLock,
# Insert, Home, PageUp
# Delete, End, PageDown
#
# Up,
# Left, Down, Right
#
# NumLock, LineFeed, ScrollUp, ScrollDown,
# F13, F14, F15, F16, F17, F18, F19, F20, F21, F22, F23, F24

[keys]
1 = 'Apostrophe'
2 = 'SemiColon'
3 = 'BackSpace'
4 = 'Enter'
5 = 'Tab'
6 = 'LeftControl'
7 = 'LeftMeta'
8 = 'LeftMeta'
9 = 'LeftShift'
10 = 'BackSpace'
11 = 'LeftMeta'
12 = 'Delete'
